[window]
width = 1600
height = 800

[simulation]
# auto_start = true
# dt = { fixed = 0.001 }
# speed_factor = 0.5
# gpu_integration = true
# gpu_bvh = true
restitution_coefficient = 0.97
global_gravity = [0, 1000]
gravitational_constant = 10000
# time_limit = 0.2
# time_limit_action = "pause"
gpu_integration_local_wg_size = 32
gpu_bvh_local_wg_size = 32

[demo]
object_radius = 10
# enable_planets = true
# randomize_positions = true
randomize_position_factor = 1
# randomize_radii = true
randomize_radius_factor = 1

[[demo.bricks]]
position = [500, 200]
size = [500, 500]
# velocity = [1, 0]
particle_radius = 3
particle_spacing = 0.01
particle_mass = 0.1

# [[demo.bricks]]
# position = [1000, 500]
# size = [500, 250]
# # velocity = [1, 0]
# particle_radius = 3
# particle_spacing = 0.01
# particle_mass = 0.1

# [[demo.bricks]]
# position = [400, 400]
# size = [600, 300]
# # velocity = [1, 0]
# particle_radius = 8
# particle_spacing = 0.01
# particle_mass = 1

# [[demo.bricks]]
# position = [700, 100]
# size = [500, 500]
# # velocity = [1, 0]
# particle_radius = 8
# particle_spacing = 1
# particle_mass = 1

# [[demo.balls]]
# position = [250, 150]
# radius = 70
# velocity = [1000, 0]
# particle_radius = 0.3
# particle_spacing = 0.1
# particle_mass = 0.1

[rendering]
# enabled = false
color = "dark"
show_edf = true
